nix-community/NixOS-WSL

configuration.nix
Hi,
Without this change I'm locked out of the root user with the default configuration.nix unless I'm missing something. It seems `wsl.exe --user root` doesn't do anything, I'm still logged in as `defaultUser`.
Fixing this problem after the fact requires re-building the tarball and reinstalling the WSL distro. Let's remove one pitfall for new users :-)
Thanks!
=> Add defaultUser to `wheel` group

build-tarball.nix, flake.nix
Also support building without Nix Flakes (again) using
```shell
nix-build -A system -A config.system.build.tarball ./nixos.nix
```
=> Support building without flake.nix

.github/workflows/main.yml, .gitignore, build-tarball.nix, configuration.nix, flake.lock, flake.nix
- Add a check to `flake.nix` which asserts that Nix source files a properly formatted using `nixpkgs-fmt`. 
- Run the check as part of the workflow
- Also execute the workflow for PRs
=> Check format in workflow

syschdemd.sh
This fixes the warnings given by perl each time a wsl container boots up
=> Set locale when running nix activate

build-tarball.nix
This sets the initial /bin/sh to syschdemd, which means that the user no longer has to manually run nix activate.
Instead the user will be logged in to the default user account.
I've tested this with the `wsl.exe --import` install method but I haven't tested if it works with DistroLauncher.
=> Avoid having to run nix activate on first run

.envrc, .github/workflows/main.yml, README.rst, build-tarball.nix, configuration.nix, default.nix, flake.lock, flake.nix, modules/build-tarball.nix, modules/docker-desktop.nix, modules/installer.nix, modules/wsl-distro.nix, nixos.nix, syschdemd.sh
The changes that I have implemented in my fork of this repo can't be separated easily anymore, so I have put all of them in one PR.
#53, #45 and #39 are integrated in this pull request
- The configuration has been split into multiple modules, which are exposed through the flake
- the system configuration accesses the flake using flake-compat, so that it can be built without a flake-enabled nix
- Optional Docker Desktop support (can be enabled in configuration.nix)
- nixos.nix has been removed in favor of using flake-compat for nix-build. The CI pipeline has been adjusted accordingly
- syschdemd.sh loads /etc/set-environment before starting a command. This makes  the WSL-Remote in VSCode work if https://github.com/msteen/nixos-vscode-server is used
- A module has been added to build an …
=> Everything that changed in my fork of this repo

build-tarball.nix, configuration.nix, flake.lock, syschdemd.sh
This PR adds support for [WSLg](https://github.com/microsoft/wslg).
GUI Applications can be launched from a shell as well as from the start menu
I added an activation script, that copies the application launchers to `/usr/share/applications` so that the installed applications will appear in the windows start menu
`syschdemd.sh` was changed to start `/bin/sh` as a login shell because the environment variables aren't present otherwise
=> Add support for WSLg

configuration.nix, syschdemd.sh
- Compared to #39: I did not hard-code anything, so there won't be an ever-growing list of environment variables we need to manually pass through.
- Compared to #40: I did not switch to `systemd-run`, therefore systemd still starts user sessions. Avoids reintroducing issues like #18 and #29.
- Compared to #41: My patch is simpler and doesn't combine `machinectl` and `systemd-run` in confusing ways.
I also added the Windows %PATH% to the Linux $PATH, so running Windows exe's doesn't require specifying the full absolute file path.
=> Yet another environment pass-through PR

modules/build-tarball.nix
This adds the `wsl.tarball.includeConfig` option, that allows the user to disable including the system config, when building a custom tarball
Closes #61
=> Allow building tarballs that do not contain the system config

modules/installer.nix, modules/wsl-distro.nix, syschdemd.nix, syschdemd.sh
Add a `/bin/mount` binary to the installer, so that WSL can correctly mount the file systems
`/etc/fstab` is not required, but an error appears if it is not present
When the shell is started in `/root`, syschdemd now silently changes to the default user's home directory, in order to prevent an error message from appearing. This happens, when WSL is started in a directory, that is not available in the guest fs
Closes #72
=> Fix Windows File Systems not being mounted on first start when using the Installer

configuration.nix, flake.nix, modules/docker-desktop.nix, modules/docker-native.nix
Addresses [#59](https://github.com/nix-community/NixOS-WSL/issues/59#issuecomment-1092657189) by overlaying legacy iptables on the docker package.
=> Add docker-native module for native docker support in NixOS

modules/wsl-distro.nix
`/mnt/wslg/runtime-dir` is owned by user ID 1000, as noted in [this post](https://github.com/microsoft/wslg/discussions/144), which is always the first user created on the system. I changed my `configuration.nix` to use a different user name by using the provided `defaultUser` parameter. However, on rebuild, this causes NixOS to create an entirely new user with ID 1001, which then causes strange behavior with wslg, because programs like emacs will emit errors like:
unable to create directory "/mnt/wslg/runtime-dir/dconf"
This is because they can't write to `runtime-dir`. The fix for this is easy: simply force the default user to have ID 1000, which fixes the problem.
=> Preserve UID for default user

modules/wsl-distro.nix
Fixes interop with latest WSL versions. Would appreciate some testing on pre-Store versions of WSL.
=> interop: enable preserveArgvZero

modules/installer.nix, modules/wsl-distro.nix
=> fix /bin/wslpath missing

modules/docker-desktop.nix
Potentially fixes #89
This is the changeset I did to fix docker-desktop on my machine. I think it needs further investigation of why I have different paths than other users. See #89 for more information.
=> fix docker-desktop systemd proxy

flake.nix, modules/interop.nix, modules/wsl-distro.nix
Due to the amount of side-effects that touching the binfmt registrations introduces (no interop in other distros, broken WSLg, etc)  it is now disabled by default. When the configuration contains another binfmt registration (and would therefore break interop) a warning is issued during evaluation
@K900
=> interop: move to its own module and disable re-registration by default

modules/wsl-distro.nix, syschdemd.nix, syschdemd.sh
The `/mnt` mount gets marked as shared in the systemd wrapper script, so that the bind mounts created by the docker desktop proxy are present outside the systemd namespace
See also #89 #90
@hschaeidt
=> docker-desktop: fix bind mounts

configuration.nix
- `environment.noXlibs` breaks often things and is a hassle to use
- `documentation.enable` having documentation available is desired
- `documentation.nixos.enable` removes the man page for nixos-rebuild which is triggered by --help
- `programs.command-not-found.enable` also command-not-found is useful
see https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/profiles/minimal.nix
=> Do not import minimal profile by default

modules/wsl-distro.nix
Do not set boot.isContainer to true, but set the required options directly. This gets around some quirks isContainer introduces in other modules (especially one in PAM that is related to solving #138). This might introduce issues related to `udev`, `audit` and `modprobe`, which get activated by removing that option; though i have not encountered any so far
=> remove boot.isContainer

flake.nix, modules/wsl-conf.nix, modules/wsl-distro.nix
Added proper types for all options that can be set in wsl.conf to avoid typos and using wrong types
=> wsl.conf: proper option types

modules/wsl-distro.nix, scripts/syschdemd.nix, scripts/syschdemd.sh
This fixes #138, by using systemd-run instead of machinectl, but breaks systemd user sessions and dbus
@K900: If we can get those to work with systemd-run, it will probably work with native systemd as well (because I think this is what MS is using as well)
=> Fix syschdemd exit code

modules/wsl-distro.nix
When native systemd integration is enabled in WSL, it looks for /bin/login to login the user.
It enables proper support for user session (dbus and systemd).
Resolves issue #165.
=> Setup /bin/login for native systemd support

scripts/syschdemd.sh
The pts should have $USER:tty permissions, not root:tty. This broke gpg with the following not very helpful error message:
gpg: signing failed: Permission denied
=> Fix permissions for files in /dev/pts

scripts/syschdemd.sh
sudo ssh with JumpHost is right now broken.
``/nix/store/x411w196j7fvznixm9517mya5g3rhnvs-syschdemd/bin/.syschdemd-wrapped: line 114: exec: exec: not found``
```
sudo NIXOS_WSL_DEBUG=1 ssh host
+ rundir=/run/nixos-wsl
+ pidfile=/run/nixos-wsl/unshare.pid
+ main -c 'exec ssh -l tunnel -W '\''[host]:22'\'' jumpHost'
+ ensure_root
+ '[' 0 -ne 0 ']'
+ '[' '!' -e /run/current-system ']'
+ '[' '!' -e /run/nixos-wsl ']'
+ is_in_container
+ '[' true == true ']'
+ '[' 2 -gt 0 ']'
+ shift
+ command='exec ssh -l tunnel -W '\''[host]:22'\'' jumpHost'
+ is_in_container
+ '[' true == true ']'
+ exec exec ssh -l tunnel -W ''\''[host]:22'\''' jumpHost
/nix/store/x411w196j7fvznixm9517mya5g3rhnvs-syschdemd/bin/.syschdemd-wrapped: line 114: exec: exec: not found
kex_exchange_identification: Connection …
```
=> Fix sudo ssh with jumpHost

modules/wsl-distro.nix
by updating the tmpfile.d rule to match the one created by upstream WSL
Or do we just want to remove this?
=> Fix X11 socket symlink creation

modules/wsl-distro.nix, scripts/native-systemd-shim/src/main.rs
=> Mount propagation fixes (and also oomd)

flake.lock
[As indicated on discourse](https://discourse.nixos.org/t/why-does-nix-flake-show-try-to-write-a-lock-file/24123) the lockfile has not been properly updated along with the flake input
=> nix flake lock

modules/wsl-distro.nix
=> Fix copy-launchers activation script

modules/wsl-distro.nix
grep adds a final newline which the second tr turns into an extra : By using a null byte and telling grep to treat it as text we can avoid this.
Also guard the grep against the alias in my shell :)
=> Don't add an extra :, make robust against grep aliases

flake.nix, scripts/native-systemd-shim/src/main.rs
The latest WSL update makes /dev/shm a mount point, not a symlink, as it should be.
Unfortunately, this does not work well with us trying to remove it. Oops.
=> fix: fix compatibility with latest WSL update

.github/workflows/main.yml, VERSION, flake.lock, flake.nix, modules/version.nix
Add a `nixos-wsl-version` command. This pr also introduces a new versioning scheme to be compatible with the version format that will be required for the Distro Launcher. The format looks as follows:
```
MAJOR.MINOR.TAG.COMMIT
e.g.
22.11.4.78
```
where `MAYOR` and `MINOR` are the NixOS version, `TAG` is incremented with every NixOS-WSL release and `COMMIT` counts the commits since that release. This version is automatically calculated in the CI pipeline. If the module is imported as a flake input or the installer tarball is build locally, the version will show as `DEV_BUILD` instead.
The output of `nixos-wsl-version` contains more information besides the calculated version and looks like this:
```
NixOS-WSL 22.11.4.77 fbe364f47cb713b759865d06e4962b9930516a18 syschdemd
```
That information …
=> nixos-wsl-version command

checks/side-effects.nix, checks/username.nix, flake.nix, modules/wsl-distro.nix, tests/username-change/username-change.Tests.ps1, tests/username-change/username-change.nix
Me with my weird system again, sorry.
=> Default user name isn't necessarily the same as user attr name

modules/wsl-conf.nix, modules/wsl-distro.nix
Fixes X11 applications on tmp-as-tmpfs setups.
=> fix: relink the X11 socket into place if needed

modules/wsl-distro.nix
We can support usbip with the Microsoft Store version of WSL (I think that's the one that introduced the change, also turned on WSLg)
Related is https://github.com/nix-community/NixOS-WSL/pull/175#discussion_r1048284393 which is where it got disabled, because it wasn't necessary rather than because it broke things
See https://github.com/nix-community/NixOS-WSL/issues/111 for NixOS-WSL usbip discussion
=> Enable udev by default (it can be useful when using usbip)

modules/installer.nix
This avoids perl outputting warnings about missing locales during the installer
=> Fix perl locale errrors in installer

modules/wsl-distro.nix
Reverts nix-community/NixOS-WSL#225
Going to revert this because it draws in firmware which is 300MB big and cannot easily be disabled.
=> Revert "Enable udev by default (it can be useful when using usbip)"

modules/wsl-distro.nix
This is more consistent with what other distros do and may (MAY!) unfuck more cases of wsl -e sh -c abuse.
=> fix: just pull in the entire environment into the /bin/sh wrapper

modules/wsl-conf.nix
=> wsl-conf: warn when networking.extraHosts has no effect

modules/wsl-distro.nix
We can generally find them in /run/current-system/sw/bin, but WSL may try to call those before activation is fully done, so make sure it can always find what it needs.
=> fix: explicitly add systemctl and grep to path in shell-wrapper

modules/wsl-distro.nix
I use home-manager to manage much of the software. This allows the default users applications be properly copied and thus end up on the start menu launchers.
=> Include per-user applications in start menu launchers

modules/build-tarball.nix
If you build your own custom tarballs this is useful.
=> Allow customizing the system config to include in the tarball

flake.lock, scripts/syschdemd.nix
Related to the discussion in #237 (though it doesn't address the original issue, so don't close that after merging this)
`getent` was moved to its own derivation and removed from `glibc` on unstable. Therefore syschdemd crashed on systems running nixos-unstable. By using the getent derivation instead, it works on 22.11, 23.05 and unstable (that's the ones I tested, it might work on older versions as well)
=> fix: getent missing in syschdemd

README.md, configuration.nix, flake.lock, flake.nix, modules/wsl-distro.nix, tests/shells.Tests.ps1
=> Bump stable to 23.05

flake.nix, modules/default.nix, modules/welcome.nix
Direct people to upgrade their systems first and link to support channels just in case.
=> feat: add welcome message

flake.nix, modules/default.nix, modules/usbip.nix
This adds a module to enable USB support via usbip together with a [usbip-win](https://github.com/dorssel/usbipd-win) running on the host.
- Adds the usbip package to be able to run adhoc usbip command e.g. (usbip list --remote 172.23.96.1)
- Enables udev
- Creates systemd services to auto-attach USB devices based on busid
One caveat with accessing USB devices is that they will require wider permissions than that will most likely be configured. For example the infrastructure provided by NixOS to enable YubiKeys will add a rule with permission mode `0660`. While when running WSL with usbip you need to set `0666` in the udev rules.
So for example to get YubiKeys working you would need something like this:
```nix
{
services = {
pcscd.enable = true;
udev = {
packages = …
```
=> Add usbip module for usb support in WSL

modules/wsl-distro.nix
which holds a reference to the kernel
On my system this results in the following change:
```
System package diff:
linux: 6.6.7 → ∅, -128630.1 KiB
```
=> Disable bootspec

.github/workflows/run_build.yml
Instead of generating a version number from the NixOS version and the number of tags, it is now generated by parsing the latest tag and replacing the last position by the number of commits since the tag. Versions would then look like this
`<NixOS version>.<major>.<minor>.<commit>`
With the new format the next release would be:
`2311.5.3.0`
=> Generate version number from tag name

modules/wsl-distro.nix
This PR introduce `wsl.useWindowsDriver` option, which enables `/usr/lib/wsl/lib` as OpenGL driver.
With the help of this PR, CUDA can be used if there is a Nvidia GPU.
```
[nixos@nixos:~]$ nvidia-smi
Thu Nov 16 05:46:07 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.05              Driver Version: 545.84       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. | …
```
=> wsl-distro: introduce `wsl.useWindowsDriver` option

modules/wsl-distro.nix
Closes #362
The code relied on `defaultUser` attribute name in `config.users.users` to be the same as the username. This is not always the case as the username can be set by `name` attribute inside the user configuration
So for following user
```nix
users.users.foo.name = "bar";
```
the `wsl.defaultUser = "foo"` works, but the `wsl.startMenuLaunchers = true` won't work because it tries to find applications folder at `/etc/profiles/per-user/foo/share` rather than
`/etc/profiles/per-user/bar/share` that is actually created.
This PR uses the `name` attribute of that user instead which should fix the issue. (tested locally, it seems to be working correctly)
=> Fix symlink creation of per-user apps/icons folder

modules/systemd/default.nix
This PR migrates from `systemd.tmpfiles.rules` to `systemd.tmpfiles.settings` to allow user overrides.
This way the `/tmp/.X11-unix` wslg mount can be disabled with:
```nix
systemd.tmpfiles.settings = {
"10-wslg-x11" = lib.mkForce {};
};
```
For reference the old and new content in `/etc/tmpfiles.d`:
old: `L /tmp/.X11-unix - - - - /mnt/wslg/.X11-unix`
new: `'L' '/tmp/.X11-unix' '-' '-' '-' '-' /mnt/wslg/.X11-unix`
=> feat: add option to disable wslg x11 mount

modules/wsl-distro.nix
When using a profile containing icons having a symlink such as:
```
/etc/profiles/per-user/USER/share/icons/hicolor -> /nix/store/fvlvfdkc9hh7icadwqxfiazifmsxprrl-home-manager-path/share/icons/hicolor
```
The merge of several rsync sources doesn't work properly. With this fix it will copy the symlinked directory instead and in that way support the rsync.
=> fix: start menu launchers rsync of directory symlinks

.github/ISSUE_TEMPLATE/bug_report.md
We are asking wsl --version in every issue anyway.
Expected behavior is often literally that what under big description is described should work or for the lazy ones ``it should work`` which we can safe.
=> Ask for output of wsl --version, remove expected behavior

modules/wsl-distro.nix
otherwise $out/lib was a symlink which the files cannot be placed into
Closes #390
=> Create directory for symlink tree

flake.nix
Removes the warning about `system.stateVersion` not being set when building tarballs with the configurations provided in `flake.nix`
=> fix: set state version when building tarballs

modules/systemd/default.nix, modules/wsl-distro.nix
Fixes #328 
Bind mount the X0 socket instead of symlinking `/tmp/.X11-unix` to make FHS environments work
=> fix: bind mount X11 socket instead of symlinking

README.md, docs/src/install.md
Hi,
I first installed NixOS-WSL according to the instructions in the README.md, and it created a NixOS folder in my Downloads folder, in which the filesystem was stored. I saw that the other WSL filesystems are located in %localappdata% (AppData\Local), so this seems like a much better instruction to give in the README file.
Also, the README include adding `--version 2`. It works, but I don't think it does anything. `wsl --help` shows that `--version` just displays the version. I checked, and the command works without the `--version 2` arguments just as well.
=> Update README.md - use %localappdata% instead of the cwd

modules/wsl-distro.nix
Fixes #448
A recent change in an upstream package makes systemd mount a `tmpfs` over `/run/user/<id>` when a user session is started. This leads to the wayland-socket to which WSL puts a symlink to into this directory, no longer being accessible.
This is fixed here by making the relevant unit no longer run if the directory is already present
=> fix: prevent systemd from hiding wayland socket

modules/usbip.nix
The nameserver does not necessarily need to be the windows host.
/cc @terlar
=> usbip: make more reliable by using default route

README.md
I've recently tried to install NixOS on a fresh installation of Windows 11. I couldn't import tarball until I install WSL either with another distro or no distro. `wsl.exe` doesn't even print `--import` as an option until it's done.
=> Add instructions to enable WSL 2

modules/systemd/native/default.nix, modules/systemd/native/wrap-shell.nix, utils/Cargo.toml, utils/src/shell_wrapper.rs
Add a wrapper around every user shell so that we can make sure that the environment gets set. `bash` does not source `/etc/bashrc` when running non-interactively, thereby breaking things like `wsl -d nixos <some command>` (unless the full path to the command is specified of course). This is not a problem for other distros, because Microsoft's `/init` binary adds some common locations to the `PATH` before starting the shell, but we don't have those here.
As a welcome side-effect, this also fixes #399
(I didn't notice that this was a problem until I tried to fix the Windows tests, because zsh doesn't have this problem. It just always sources its config files)
=> fix: non-interactive bash

.github/workflows/run_build.yml, .github/workflows/run_tests.yml, flake.nix, tests/lib/lib.ps1
GitHub recently upgraded their free-tier runners (Standard GitHub-hosted runners).
https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/
The new VMs support nested virtualization, although it is not documented in the blog post. This draft enables the tests on Windows, but not all of them are working.
1. `sudo nixos-rebuild switch` seems to hang in various tests for some reason.
2. `docker/docker.Tests.ps1` fails. Here are the first two statements from the output:
```
invalid pointererror: builder for '/nix/store/pq20h6rhjkndrl1x4d7rm63ahl62hb6j-nixos-23.11.drv' failed due to signal 11 (Segmentation fault)
error: program '/nix/store/vgncjxxj6vfzynnh0si7c67466m1sm37-nix-2.18.1/bin/nix-env' failed with exit code 100
```
See also [my last …
=> Enable tests on Windows

.github/workflows/run_build.yml, .github/workflows/run_tests.yml, .vscode/settings.json, flake.nix, tests/README.md, tests/basic-functionality.Tests.ps1, tests/docker/docker-native.nix, tests/docker/docker.Tests.ps1, tests/exit-codes.Tests.ps1, tests/lib/Dockerfile, tests/lib/lib.ps1, tests/login-shell/login-shell.Tests.ps1, tests/login-shell/session-variables.nix, tests/shells.Tests.ps1, tests/systemd-services.Tests.ps1, tests/systemd-user.Tests.ps1, tests/username-change/username-change.Tests.ps1, tests/username-change/username-change.nix
=> test: Make tests work on Windows with native systemd

.github/workflows/on_release.yml, .github/workflows/run_build.yml, .github/workflows/run_package.yml, .github/workflows/run_tests.yml, docs/src/building.md, flake.nix, modules/systemd/syschdemd/default.nix, tests/README.md
This should ideally be merged after #466
=> syschdemd: add deprecation notice

modules/24.05-compat.nix, modules/default.nix, modules/wsl-distro.nix
As of https://github.com/NixOS/nixpkgs/pull/320228, `hardware.opengl` was renamed to `hardware.graphics`, causing definitions of the former to trigger an evaluation warning on the current nixos-unstable channel. Aliases are applied conditionally for these new options to continue supporting 24.05
edit: fixes #498
=> Resolve renamed option hardware.opengl -> hardware.graphics

utils/src/shim.rs
This makes it so that the systemd logs will be availably by running `dmesg` in another distro or the system distro
Closes #529
=> shim: make systemd log to kmsg

modules/docker-desktop.nix
Fixes #235
Tested extensively with [Docker Desktop 4.34](https://docs.docker.com/desktop/release-notes/) and NixOS 24.05.
Please consider each commit individually during the review. Each of them provides a justification about the changes being performed.
=> Update Docker Desktop integration

modules/recovery.nix
config.system.build.nixos-enter is deprecated.
=> recovery: prefer nixos-enter from pkgs if available

modules/systemd/native/wrap-shell.nix, modules/wsl-distro.nix
Fixes the environment not being available to commands where /bin/sh is called directly. This happens for example when trying to switch into a dev container in a VSCode attached to the WSL distro. Fixes #555
=> shell-wrapper: wrap /bin/sh

modules/wsl-conf.nix
Closes #559
Pretty much what it says on the tin
=> wslConf: convert to freeform type

modules/24.05-compat.nix
Fixes building on NixOS 24.05 (for me - [nixos-modules](https://github.com/NuschtOS/nixos-modules) uses some of these options and breaks if both of them exists but only partially)
=> 24.05-compat: sync with nixos-hardware

docs/src/how-to/vscode.md
Mic rewrote nix-ld and integrated the fork into it and that is the current default implementation in nixos-unstable
=> Remove mentions of nix-ld-rs

README.md, docs/src/install.md
The options such as `--version` should be placed at the end of the command. Updated the README to reflect the correct command syntax.
=> docs: fix WSL import command option order

modules/wsl-distro.nix
Disable `populateBin` when `envfs` is enabled
=> Support envfs

modules/usbip.nix
This fixes some bugs that I discovered in the default command.
The nix string escaping was wrong so the `\` got lost and when I tested this the command had a trailing space that made it fail still.
Also this didn't work when I was using network-mode mirrored since it includes metric in the output:
```
$ ip route list
default via 192.168.1.1 dev eth0 proto kernel metric 35
192.168.1.0/24 dev eth0 proto kernel scope link metric 291
192.168.1.1 dev eth0 proto kernel scope link metric 35
```
This also adds a target so you can batch restart the services. This is handy when having multiple YubiKeys and or switching between VPN. Perhaps there could even be some auto-restart thing. Will have to think about if that is a hack or not.
=> usbip: fix default snippetIpAddress command

utils/src/shell_wrapper.rs
=> fix: shell wrapper overwrites $SHELL

modules/usbip.nix
The upstream script changed to a relative path based on the working directory. This patches the code to use the lookup by PATH instead.
Fix #594
=> usbip: fix auto-attach script

flake.lock, flake.nix
flake-utils' main utility is making flakes easier to make. but more modernly they don't provide much utility above of overrideable systems, which is not being utlised here since `eachSystem` is being used. So instead lets remove the input and vendor our own `forAllSystems` function to recreate what we previously used flake-utils for.
=> refactor: drop flake-utils

README.md, docs/src/install.md
If there is a leading backslash `wsl` will fail with help-text.
Fixes #606
=> Fix PowerShell syntax issue in README

.github/workflows/on_release.yml, .github/workflows/run_build.yml, .github/workflows/run_checks.yml, .github/workflows/run_package.yml, .gitignore, Launcher/Launcher-Appx/Launcher-Appx.wapproj, Launcher/Launcher/src/Helpers/InstallationHelper.cs, README.md, docs/src/building.md, docs/src/install.md, modules/build-tarball.nix, tests/README.md, tests/lib/lib.ps1
Basically this is just a renamed version of the existing `.tar.gz` with a manifest file bundled in, allowing for a more convenient installation.
See https://learn.microsoft.com/en-us/windows/wsl/build-custom-distro
=> Distribute as .wsl file instead of .tar.gz

modules/wsl-distro.nix
It isn't actually necessary, lingering is just completely broken with how current WSL handles runtime directories.
=> wsl-distro: drop user-runtime-dir hack

modules/wsl-conf.nix
With https://github.com/nix-community/NixOS-WSL/pull/636 the regex was altered, but the regex is illegal on darwin, beacuse of the empty regex. Ordinary `nix flake check` will trigger a failure see [my github actions run](https://github.com/isabelroses/dotfiles/actions/runs/13992975191/job/39180939977). Hopefully this fixes that. However, I have not tested it out on nixos wsl with a `/` only mount.
=> wsl-conf: alter regex to stop tripping up on darwin

.github/workflows/run_tests.yml, modules/build-tarball.nix
The docs actually already say this is possible 🤷
=> Allow setting wsl default user in the default nix config of the generated tarball

modules/usbip.nix
```
unit-script-usbip-auto-attach_-start> building '/nix/store/dd4ssa8fni4gv3zg79p20pbi8d0k81s5-unit-script-usbip-auto-attach_-start.drv' unit-script-usbip-auto-attach_-start>
unit-script-usbip-auto-attach_-start> In /nix/store/fxkgxc0yzwcdqklcyd5y54gfi13n5ack-unit-script-usbip-auto-attach_-start/bin/usbip-auto-attach_-start line 10: unit-script-usbip-auto-attach_-start> source /nix/store/3l16mhbr2d8kyn7r3x6dr3qr4vz8pbdi-nll5ayjp1474ax1pyq3qf52arn438dn8-auto-attach.sh "$ip" "$busid"
unit-script-usbip-auto-attach_-start>        ^-- SC1091 (info): Not following: /nix/store/3l16mhbr2d8kyn7r3x6dr3qr4vz8pbdi-nll5ayjp1474ax1pyq3qf52arn438dn8-auto-attach.sh was not specified as input (see shellcheck -x).
unit-script-usbip-auto-attach_-start>
unit-script-usbip-auto-attach_-start> For more …
```
=> Fix usbip when enableStrictShellChecks is turned on

modules/systemd/native/default.nix
This will allow us to make files available in `/sbin` using `extraBin`. usbip needs `/sbin/modprobe` to load `vhci_hcd` on demand
=> merge /bin and /sbin

.github/workflows/on_push.yml, .github/workflows/run_validate.yml, modules/build-tarball.nix, modules/wsl-distro.nix
The WSL repo contains a script called `validate-modern.py` that can be used to verify if a distribution tarball complies with WSL's expectations. This adds a test for that to the CI and makes the produced tarballs compliant
=> Make .wsl file pass the validation script
