- README.rst
Added a detailed list of steps needed to run this into README.rst
> Document installation procedure

- build-tarball.nix
Also include the system configuration in the tarball which was used to create it.
> Include the system configuration in the tarball

- syschdemd.sh
> Fix syschdemd failing on first launch with installer

- modules/wsl-distro.nix
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa bash aaaaaaaaaaaaaaaaaaaaaaa
> interop: fix hacks

- modules/wsl-distro.nix
This adds support for running applications that use OpenGL with WSLg.
See also: #88
> Enable opengl support

- modules/wsl-distro.nix
> Fix eval by disabling module completely when wsl.enable = false

- modules/wsl-distro.nix
> Fix setting custom nameservers through networking.nameservers

- README.md
- configuration.nix
I had only updated the flake input in #177, this also changes the version in `README.md` and `system.stateVersion` in `configuration.nix`
> Update to 22.11 in README and stateVersion

- scripts/native-systemd-shim/src/main.rs
Work around a bug that seems to happen sometimes when the container is restarted.
> native-systemd-shim: clean up /dev/shm correctly when it's a directory

- flake.lock
- modules/wsl-distro.nix
> Use upstream settings instead of workarounds to disable unsupported settings

- scripts/syschdemd.sh
- tests/lib/lib.ps1
- tests/login-shell/login-shell.Tests.ps1
- tests/login-shell/session-variables.nix
- tests/shells.Tests.ps1
> Launch commands through a login shell

- modules/wsl-distro.nix
Turns out that it couldn't be removed in #175
> Silence bootloader warning again

- checks/rustfmt.nix
- flake.nix
- scripts/native-utils/src/split_path.rs
> fix(split-paths): use standard library tools, fix shell quoting better

- flake.nix
> Add default as an export from nixosModules

- modules/wsl-distro.nix
> Add defaultText to extraBin.name

- modules/wsl-distro.nix
This PR addresses https://github.com/nix-community/NixOS-WSL/pull/339#discussion_r1441907386
> Hard-code file names when making symbolic links for drivers

- modules/wsl-distro.nix
> Fix /tmp/.X11-unix

- .github/workflows/run_docs.yml
- docs/book.toml
- docs/src/SUMMARY.md
- docs/src/building.md
- docs/src/design.md
- docs/src/how-to/README.md
- docs/src/how-to/change-username.md
- docs/src/how-to/nix-flakes.md
- docs/src/how-to/vscode.md
- docs/src/troubleshooting/README.md
> More documentation

- .github/workflows/on_release.yml
Fixes attaching the msixbundle to a release and adds a launcher bundle zip file
> fix release ci

- utils/src/shell_wrapper.rs
> fix: make wrapper not crash if logger setup fails

- modules/systemd/native/default.nix
This is an alternative to https://github.com/NixOS/nixpkgs/pull/265866
> Create /run/booted-system symlink

- flake.nix
- modules/wsl-distro.nix
- tests/systemd-services.Tests.ps1
> Fix cyclic dependency in systemd units. Add test to check for that

- README.md
add powershell explicitly (otherwise if called in CMD, $env:USERPROFILE will not expand)
> Add explicit powershell

- modules/wsl-conf.nix
> fix: update wsl.wslConf.automount.root regex to allow / 
